### ISSUE TITLE
カテゴリのメニューなどのヘルパを用意する

### ISSUE THREAD

**Issue by myokoym** [bm-sms/uramon-article-viewer#3]
- 基本的にHTMLはarticle-viewerで組み立てる
  - デフォルトのパーツを提供して、使う側でオブジェクトを直接触らなくていいように

**Comment by myokoym** [comment]
commit 11a0e9f5ba665ee49c4f2856bb22fa4476380910 でメニューのヘルパーを追加したが、以下のTODOが残っている:
- リンク先のパスの設定
- リンク先のコントローラーの作成
- 薄いRailsアプリから呼び出すテスト

**Comment by myokoym** [comment]
> - リンク先のパスの設定
> - リンク先のコントローラーの作成
> - 薄いRailsアプリから呼び出すテスト

上記は対応していました。

残TODO:
- [x] `@categories`がない場合にNoMethodErrorになる
- [ ] カテゴリ別記事一覧のURLにslugを使う
- [x] 最近の記事のヘルパ化 ref: #1
- [x] パンくずリストのヘルパ化 ref: #4

**Comment by tricknotes** [comment]
つづきはこちらで: https://github.com/bm-sms/uramon-article-viewer/issues/9

**Comment by mtsmfm** [comment]
> カテゴリ別記事一覧のURLにslugを使う

これは #9 でやるのでこっちは close
